language: node_js
sudo: false
node_js:
  - "10"
  - "14"

before_script:
  - npm install

script:
  - npm run eslint
  - npm test
  # - npm run-script coverage

after_success: npm run coverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6d3795933a79ee05ae7a
    on_success: change
    on_failure: always
    on_start: never
